#' Generate Startup Message
#'
#' This function generates a startup message to be displayed when the package is loaded.
#' It includes the package version and a custom ASCII art message.
#'
#' @return A character string containing the startup message.
#' @importFrom utils packageVersion
#' @importFrom cli col_blue
#'
#' @noRd
startupMessage <- function(){
  version <- utils::packageVersion("exactt")
  
  if(interactive()){
    nbar <- nchar('`Y8bod8P\' o88\'   888o `Y888\"\"8o `Y8bod8P\'   \"888\"   \"888\"') - nchar("\u2500\u2500\u2500\u2500 It's Exact. ") - nchar(paste0(" Version ", version))
    nbar <- ifelse(nbar >= 1, yes = nbar, no = 5)
    bars <- paste0(rep("\u2500", nbar), collapse = "")
    
    # https://patorjk.com/software/taag/#p=display&f=Roman&t=exactt
    # Font Name: 'Roman'
    ascii_art <- paste0(
      "\n                                              ", cli::col_blue('.'), "       ", cli::col_red('.'), 
      "\n                                            ", cli::col_blue('.o8'), "     ", cli::col_red('.o8'), 
      "\n ", cli::col_blue('.ooooo.  oooo    ooo  .oooo.    .ooooo.  .o888oo'), " ", cli::col_red('.o888oo'),
      "\n", cli::col_blue('d88\' `88b  `88b..8P\'  `P  )88b  d88\' `\"Y8   888'), "     ", cli::col_red('888'), 
      "\n", cli::col_blue('888ooo888    Y888\'     .oP\"888  888         888'), "     ", cli::col_red('888'), 
      "\n", cli::col_blue('888    .o  .o8\"\'88b   d8(  888  888   .o8   888 .'), "   ", cli::col_red('888 .'),
      "\n", cli::col_blue('`Y8bod8P\' o88\'   888o `Y888\"\"8o `Y8bod8P\'   \"888\"'), "   ", cli::col_red('\"888\"'),
      "\n"
    )
    
    
    msg <- cli::col_blue(paste0(ascii_art, 
                                "\n\u2500\u2500\u2500\u2500 It's ",
                                cli::col_red("exact"),
                                ". ", bars, " Version ", version))
  } else{
    msg <- paste("Package 'exactt' | Version", version)
  }
  
  return(msg)
}

#' @title Package Startup Hook
#' @description This function is run automatically when the package is loaded. It displays the startup message generated by `startupMessage`.
#' @param lib The library path.
#' @param pkg The package name.
#' @noRd
.onAttach <- function(lib, pkg) {
  packageStartupMessage(startupMessage())
}

#' @title Package Load Hook
#' @description This function is called when the package is loaded. It registers the S3 method for printing objects of class \code{et}.
#' @param libname The library name where the package is installed.
#' @param pkgname The name of the package.
#' @keywords internal
.onLoad <- function(libname, pkgname) {
  registerS3method("print", "et", print.et)
}
